[tool.ruff]
line-length = 180
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I"] # Enable Error, Flake8, Warnings, and Isort rules
ignore = []
exclude = ["alembic/versions"]

[tool.ruff.lint.per-file-ignores]
"alembic/*" = ["I001", "W293", "W292", "W291", "F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
files = [
    "main.py",
    "config.py",
    "container.py",
    "cogs/",
    "database/",
    "interfaces/",
    "services/",
    "tests/",
    "utils/",
    "views/",
]
exclude = ["alembic/"]

