"""Add guild relationship to audit log

Revision ID: 6a807c3a2fed
Revises: 685c8c97adf0
Create Date: 2025-07-21 18:10:32.420766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a807c3a2fed'
down_revision: Union[str, Sequence[str], None] = '685c8c97adf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_log_entries', 'guilds', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_log_entries', type_='foreignkey')
    # ### end Alembic commands ###
