"""Add guild_id to voice_channels table

Revision ID: e2e16b7c49e6
Revises: 6a807c3a2fed
Create Date: 2025-07-23 18:36:14.379649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e16b7c49e6'
down_revision: Union[str, Sequence[str], None] = '6a807c3a2fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_channels', sa.Column('guild_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_voice_channels_guild_id'), 'voice_channels', ['guild_id'], unique=False)
    op.create_foreign_key(None, 'voice_channels', 'guilds', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_channels', type_='foreignkey')
    op.drop_index(op.f('ix_voice_channels_guild_id'), table_name='voice_channels')
    op.drop_column('voice_channels', 'guild_id')
    # ### end Alembic commands ###
