"""Add cleanup_on_startup flag to guilds

Revision ID: fe6022cb39e8
Revises: e2e16b7c49e6
Create Date: 2025-07-23 20:30:53.837899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6022cb39e8'
down_revision: Union[str, Sequence[str], None] = 'e2e16b7c49e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add the column, allowing it to be nullable temporarily and setting a server-side default for new rows.
    op.add_column('guilds', sa.Column('cleanup_on_startup', sa.Boolean(), nullable=True, server_default=sa.true()))

    # Step 2: Update all existing rows where the new column is currently NULL to have a default value of True.
    op.execute('UPDATE guilds SET cleanup_on_startup = TRUE WHERE cleanup_on_startup IS NULL')

    # Step 3: Now that all rows have a value, alter the column to enforce the NOT NULL constraint.
    op.alter_column('guilds', 'cleanup_on_startup', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'cleanup_on_startup')
    # ### end Alembic commands ###
