name: VoiceMaster CI & Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint with Ruff and Mypy
        run: docker compose run --rm lint

      - name: Run tests and generate coverage report
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: voicedb_test
          DISCORD_TOKEN: dummy_token
        run: docker compose run --rm test
